receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 
        
processors:
  batch:
  
exporters:
  debug:
    verbosity: detailed    
  prometheusremotewrite: #prometheusremotewrite to push the metrics to Prometheus server
    endpoint: "http://prometheus:9090/api/v1/write"    
  prometheus:  #Prometheus exporter to allow scraping by a Prometheus server.
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true  
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true        
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true        
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto 
  otlphttp:
    endpoint: "http://loki:3100/otlp"  
    
service:
  telemetry: #to activate open telemetry internal telemetry data
	logs:
	  level: debug
    metrics: #Internal metrics are exposed using a Prometheus interface which defaults to port 8888, define in the prom config file to scrape
	  level: detailed
			
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
    traces:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlp/tempo, otlp/jaeger, zipkin, debug]
    metrics:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [prometheus, prometheusremotewrite, debug]  