receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318 
        
processors:
  batch:
  
exporters:
  debug:
    verbosity: detailed 
    
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write" 
     
  prometheus:
    endpoint: "0.0.0.0:8889"
     
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true   
        
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true 
         
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto  
    
  otlphttp:
    endpoint: "http://loki:3100/otlp"  
    

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
    traces:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlp/tempo, otlp/jaeger, zipkin, debug]
    metrics:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [prometheus, prometheusremotewrite, debug]  