apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:    
  - https://github.com/nagarjuna-guntu/gateway-service/k8s?ref=main
  
patchesStrategicMerge:
  - patch-env.yml
  
configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: gateway-config
  
images:
  - name: gateway-service
    newName: ghcr.io/polarbookshop/gateway-service
    newTag: latest

replicas:
  - name: gateway-service
    count: 1