
scrape_configs:  
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090'] #Self-scrapping the Prometheus server
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ['collector:8889'] #Scraping the Prometheus exporter in the OpenTelemetry collector
      
  
