apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          resources:
            requests:
              cpu: 0.1
              memory: 756Mi
            limits:
              cpu: 2
              memory: 756Mi
