apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:    
  - https://github.com/nagarjuna-guntu/order-service/k8s?ref=main
  
patchesStrategicMerge:
  - patch-env.yml
  - patch-volumes.yml
  - patch-resources.yml 
  
configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: order-config
  
images:
  - name: order-service
    newName: ghcr.io/polarbookshop/order-service
    newTag: latest

replicas:
  - name: order-service
    count: 1