apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:    
  - https://github.com/nagarjuna-guntu/catalog-service/k8s?ref=main
  
patchesStrategicMerge:
  - patch-env.yml
  - patch-probes.yml
  
configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: catalog-config
  
images:
  - name: catalog-service
    newName: ghcr.io/polarbookshop/catalog-service
    newTag: latest

replicas:
  - name: catalog-service
    count: 2